export const UZBEK_CITIES: { value: string; label: string }[] = [
  { value: "Toshkent",   label: "Toshkent" },
  { value: "Samarqand",  label: "Samarqand" },
  { value: "Namangan",   label: "Namangan" },
  { value: "Andijon",    label: "Andijon" },
  { value: "Farg'ona",   label: "Farg'ona" },
  { value: "Buxoro",     label: "Buxoro" },
  { value: "Nukus",      label: "Nukus" },
  { value: "Qarshi",     label: "Qarshi" },
  { value: "Jizzax",     label: "Jizzax" },
  { value: "Termiz",     label: "Termiz" },
  { value: "Navoiy",     label: "Navoiy" },
  { value: "Urganch",    label: "Urganch" },
  { value: "Guliston",   label: "Guliston" },
  { value: "Chirchiq",   label: "Chirchiq" },
  { value: "Kogon",      label: "Kogon" },
  { value: "Marg'ilon",  label: "Marg'ilon" },
  { value: "Qo'qon",     label: "Qo'qon" },
  { value: "Olmaliq",    label: "Olmaliq" },
  { value: "Bekobod",    label: "Bekobod" },
]
